// GENERATED — classification of every tool registered in src/index.ts (as of 2026-07-10)
// against the PRD's tool-eligibility matrix (docs/superpowers/specs/2026-07-10-findings-middleware-phase4-design.md).
// Do not hand-edit the classification of an existing tool without updating the design doc's table.
// A completeness test (test/findings/toolManifest.test.mjs) fails if a registered tool has no entry here.

export type ToolType = "audit" | "compliance" | "health_check" | "inventory" | "action" | "config_write" | "read_only_query" | "reporting_export";

export interface ToolFindingAdapter {
  resultField: string;
  findingType: string;
  category: string;
  severity: "danger" | "warning" | "info";
  serialField: string | null;
  conditionField?: string;
  // If set, only emit a finding when row[conditionField] is one of these string
  // values -- for fields that are a string enum, not a boolean (e.g. a "warning"
  // field with values like "ok"/"renew_soon"/"expired"). If conditionField is set
  // but conditionValues is not, falls back to plain truthiness of row[conditionField].
  conditionValues?: string[];
  messageTemplate: string;
}

export interface ToolManifestEntry {
  toolType: ToolType;
  publishable: boolean;
  supportsAutoPublish: boolean;
  adapters?: ToolFindingAdapter[];
}

export const TOOL_MANIFEST: Record<string, ToolManifestEntry> = {
  "assign_app_to_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "assign_custom_profile_to_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "assign_declaration_to_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "assign_device_to_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "assign_profile_to_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "assign_profile_to_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "build_certificate_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_content_filter_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_custom_declaration_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_filevault_escrow_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_firewall_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_mobileconfig": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_passcode_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_restrictions_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_scep_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_software_update_settings_declaration": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_vpn_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_webclip_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "build_wifi_profile_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "cancel_script_job": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "check_for_update": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "clear_firmware_password": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "clear_passcode": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "clear_recovery_lock_password": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "clear_restrictions_password": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "clone_assignment_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_app": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_assignment_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_custom_attribute": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_custom_configuration_profile": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_custom_declaration": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_managed_app_config": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_safari_bookmarks_declaration": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_script": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "create_script_job": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "delete_app": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_assignment_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_custom_attribute": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_custom_configuration_profile": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_custom_declaration": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_device_user": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_enrollment": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_managed_app_config": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "delete_script": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "disable_activation_lock": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "disable_bluetooth": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "disable_lost_mode": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "disable_remote_desktop": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "download_custom_configuration_profile": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "download_custom_declaration": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "enable_bluetooth": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "enable_lost_mode": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "enable_remote_desktop": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "generate_report": { toolType: "reporting_export", publishable: false, supportsAutoPublish: false },
  "get_account": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_activation_lock_status": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_api_coverage": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_app": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_app_coverage": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_app_install_failures": { toolType: "health_check", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "failures", findingType: "app_install_failure", category: "Applications", severity: "warning", serialField: null, messageTemplate: "{app_name} install {status} on device {device_id}" },
    ] },
  "get_app_size_footprint": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_app_version_drift": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_apple_device_management_schema": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_apps_by_publisher": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_assignment_group": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_assignment_group_drift": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_battery_health_report": { toolType: "health_check", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "devices", findingType: "battery_health", category: "Battery", severity: "warning", serialField: "serial", messageTemplate: "{name} flagged: {reason}" },
    ] },
  "get_certificate_expiration_audit": { toolType: "compliance", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "", findingType: "certificate_expiring", category: "Certificates", severity: "warning", serialField: null, conditionField: "warning", conditionValues: ["renew_soon", "renew_now", "expired"], messageTemplate: "APNs certificate for {apple_id} expires in {days_until_expiry} days ({warning})" },
    ] },
  "get_compliance_violators": { toolType: "compliance", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "violators", findingType: "compliance_violation", category: "Compliance", severity: "warning", serialField: "serial", messageTemplate: "{name} fails: {failures}" },
    ] },
  "get_custom_attribute": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_custom_declaration": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_dep_device": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_dep_device_status": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_dep_drift": { toolType: "compliance", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "devices", findingType: "dep_drift", category: "DEP", severity: "warning", serialField: "serial", messageTemplate: "{name} DEP profile assignment drifted" },
    ] },
  "get_dep_server": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_dep_unassigned": { toolType: "compliance", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "devices", findingType: "dep_unassigned", category: "DEP", severity: "info", serialField: "serial", messageTemplate: "{name} is a DEP device not yet assigned" },
    ] },
  "get_device": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_device_attribute_values": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_device_full_profile": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_device_group": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_device_installed_apps": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_device_logs": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_device_profiles": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_device_user_count_outliers": { toolType: "health_check", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "devices", findingType: "user_count_outlier", category: "Compliance", severity: "info", serialField: "serial", messageTemplate: "{name} has {user_count} local user accounts" },
    ] },
  "get_device_users": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_devices_missing_profile": { toolType: "compliance", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "missing_devices", findingType: "missing_profile", category: "Compliance", severity: "warning", serialField: "serial", messageTemplate: "{name} is missing the required profile" },
    ] },
  "get_enrollment": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_enrollment_token_audit": { toolType: "compliance", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "enrollments", findingType: "stale_enrollment", category: "Enrollment", severity: "info", serialField: null, conditionField: "stale", messageTemplate: "Enrollment {id} has not been used recently" },
    ] },
  "get_fleet_summary": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_group_attribute_values": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_inactive_assignment_groups": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_installed_app": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_log": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_lost_mode_devices": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_managed_app_config_templates": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_alerts": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_apple_care": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_client_facts": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_command_status": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_compliance": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_dashboard_trend": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_device_resources": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_mcp_findings": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_runner_status": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_supplemental_data": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_supplemental_overview": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_supplemental_status": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_munkireport_sync_health": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_network_summary": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_orphaned_apps": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_orphaned_profiles": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_os_eligibility": { toolType: "compliance", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "devices", findingType: "os_upgrade_available", category: "OS", severity: "info", serialField: "serial", conditionField: "upgrade_available", messageTemplate: "{name} is eligible for a macOS upgrade" },
    ] },
  "get_pending_commands": { toolType: "health_check", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "devices", findingType: "pending_command", category: "Commands", severity: "info", serialField: null, messageTemplate: "{pending_count} unacknowledged command(s), oldest sent {oldest_sent_at}" },
    ] },
  "get_profile": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_push_certificate": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_recently_enrolled": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_script": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_script_job": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_security_posture": { toolType: "compliance", publishable: true, supportsAutoPublish: false },
  "get_signed_csr": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "get_stale_devices": { toolType: "health_check", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "devices", findingType: "stale_device", category: "Health", severity: "warning", serialField: "serial", messageTemplate: "{name} has not checked in for {days_since} days" },
    ] },
  "get_storage_health": { toolType: "health_check", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "low_disk_devices", findingType: "low_disk_space", category: "Storage", severity: "warning", serialField: "serial", messageTemplate: "{name} has only {available_gb} GB free" },
      { resultField: "low_battery_devices", findingType: "low_battery", category: "Battery", severity: "warning", serialField: "serial", messageTemplate: "{name} battery at {battery_level_pct}%" },
    ] },
  "get_supervision_drift": { toolType: "compliance", publishable: true, supportsAutoPublish: true,
    adapters: [
      { resultField: "devices", findingType: "supervision_drift", category: "Compliance", severity: "warning", serialField: "serial", messageTemplate: "{name} is DEP-enrolled but not supervised" },
    ] },
  "get_top_installed_apps": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_unmanaged_apps": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "get_user_attribution": { toolType: "inventory", publishable: true, supportsAutoPublish: false },
  "list_app_installs": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_apps": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_assignment_groups": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_custom_attributes": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_custom_configuration_profiles": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_custom_declarations": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_dep_devices": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_dep_servers": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_device_groups": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_devices": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_enrollments": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_logs": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_managed_app_configs": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_profiles": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_script_jobs": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "list_scripts": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "lock_device": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "play_lost_mode_sound": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "push_apps_to_group": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "push_managed_app_configs": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "push_message": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "push_munkireport_findings": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "refresh_cellular_plans": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "refresh_device_inventory": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "refresh_munkireport_supplemental": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "request_app_management": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "request_munkireport_sync": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "restart_device": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "rotate_admin_password": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "rotate_filevault_recovery_key": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "rotate_firmware_password": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "rotate_recovery_lock_password": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "run_config_backup": { toolType: "reporting_export", publishable: false, supportsAutoPublish: false },
  "run_device_logs_audit": { toolType: "audit", publishable: true, supportsAutoPublish: false },
  "run_fleet_audit": { toolType: "audit", publishable: true, supportsAutoPublish: false },
  "run_inventory_report": { toolType: "reporting_export", publishable: false, supportsAutoPublish: false },
  "run_report_diff": { toolType: "reporting_export", publishable: false, supportsAutoPublish: false },
  "search_apple_device_management_schemas": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "send_enrollment_invitation": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "set_admin_password": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "set_attribute_for_multiple_devices": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "set_device_attribute_value": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "set_group_attribute_value": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "set_managed_app_config_schema": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "set_time_zone": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "shutdown_device": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "sync_dep_server": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "sync_device": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "sync_profiles_in_group": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "unassign_app_from_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "unassign_custom_profile_from_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "unassign_declaration_from_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "unassign_device_from_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "unassign_profile_from_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "unassign_profile_from_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "unenroll_device": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "uninstall_app": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "update_account": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "update_app": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "update_apps_in_group": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "update_assignment_group": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "update_custom_attribute": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "update_custom_configuration_profile": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "update_custom_declaration": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "update_device": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "update_installed_app": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "update_lost_mode_location": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "update_os": { toolType: "action", publishable: true, supportsAutoPublish: false },
  "update_script": { toolType: "config_write", publishable: false, supportsAutoPublish: false },
  "validate_apple_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "verify_webhook_payload": { toolType: "read_only_query", publishable: false, supportsAutoPublish: false },
  "wipe_device": { toolType: "action", publishable: true, supportsAutoPublish: false },
};
